language: php
php:
 - 5.6

sudo: false

notifications:
  email:
    secure: "DRcGoU61qyeTqJdZL59LDyz2au2XEGgrUHPXlUilavPqgWvkdHn2+QWUmVWOHPYr1Ixt+enO9bRmTCO3VJAIHsAsBYF3dQjGG2MGPWwe8BJC3NLb0BzeH1F6buqZyYMT1qnfqQQngn48JDEjkP1pnBdHwWB9wRhrKnlKVn7NPkYPkUrdQetPKQNTazNtHZ4oack0xsKyCmfI5LlBbhZ47WS8nXc6dGL++pQKbtckdg8rPmkgKr2CDF0eJEaSDIVGUCq4BNgoyaMJ/lLlBHnmNeVXAK67rdlQDDfb9nnOtuTLIr/0rdpihRGjmd6I7jSzmWFlEyDCZ3eVu56K1kNG4I6IKXeGy93gtRd2gFkBt+JIyMrHxRHyRYHXPDb+PH/NOlTj7WyP+o2LSfSp+YsxRhGWJeYM77Yuqv/MbVgKzBHxRNfENXa0Nx17ySTbGLMtpVhGSl2/blQPn+BmK8dl65+ao0lRlZRPsjwlCoCdvZoNCAk3Uw2FmGt5htJM9lVPziNmonS/h2hv1mR/FCu2DbV4+Dob1v2uLD8B4TW1EiFoUusK1pk2H6YEdgxFtfW/f7TLmTdj69dOX7aFgjCArhIXdnCWbcnG18oc0Subk8uechReS1oAXQ70KhiS2wcc793uNUJicNiSEh+xSAFXkMD42H2SfcaXJULf4PvPUHA="

env:
  - DB=MYSQL CORE_RELEASE=3.7

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.7
    - php: 7.2
      env: DB=MYSQL CORE_RELEASE=3.7
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=3.7
    - php: 5.6
      env: DB=SQLITE3 CORE_RELEASE=3.7
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.6

before_script:
  - composer self-update || true
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss
  - composer install

script:
  - vendor/bin/phpunit gridfield-deleted-items/tests