sudo: false

language: php

php:
  - 5.6

env:
  - DB=MYSQL CORE_RELEASE=3.5

matrix:
  include:
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=3.5
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.5
    - php: 5.6
      env: DB=SQLITE3 CORE_RELEASE=3.5
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.4

before_script:
  - composer self-update || true
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss
  - composer install

script:
  - vendor/bin/phpunit gridfield-deleted-items/tests